# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.20

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/yq/tmp/libjuice

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/yq/tmp/libjuice

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/yq/tmp/libjuice/CMakeFiles /home/yq/tmp/libjuice//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/yq/tmp/libjuice/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named juice

# Build rule for target.
juice: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 juice
.PHONY : juice

# fast build rule for target.
juice/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice.dir/build.make CMakeFiles/juice.dir/build
.PHONY : juice/fast

#=============================================================================
# Target rules for targets named juice-static

# Build rule for target.
juice-static: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 juice-static
.PHONY : juice-static

# fast build rule for target.
juice-static/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice-static.dir/build.make CMakeFiles/juice-static.dir/build
.PHONY : juice-static/fast

#=============================================================================
# Target rules for targets named juice-tests

# Build rule for target.
juice-tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 juice-tests
.PHONY : juice-tests

# fast build rule for target.
juice-tests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice-tests.dir/build.make CMakeFiles/juice-tests.dir/build
.PHONY : juice-tests/fast

src/addr.o: src/addr.c.o
.PHONY : src/addr.o

# target to build an object file
src/addr.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice.dir/build.make CMakeFiles/juice.dir/src/addr.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice-static.dir/build.make CMakeFiles/juice-static.dir/src/addr.c.o
.PHONY : src/addr.c.o

src/addr.i: src/addr.c.i
.PHONY : src/addr.i

# target to preprocess a source file
src/addr.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice.dir/build.make CMakeFiles/juice.dir/src/addr.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice-static.dir/build.make CMakeFiles/juice-static.dir/src/addr.c.i
.PHONY : src/addr.c.i

src/addr.s: src/addr.c.s
.PHONY : src/addr.s

# target to generate assembly for a file
src/addr.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice.dir/build.make CMakeFiles/juice.dir/src/addr.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice-static.dir/build.make CMakeFiles/juice-static.dir/src/addr.c.s
.PHONY : src/addr.c.s

src/agent.o: src/agent.c.o
.PHONY : src/agent.o

# target to build an object file
src/agent.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice.dir/build.make CMakeFiles/juice.dir/src/agent.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice-static.dir/build.make CMakeFiles/juice-static.dir/src/agent.c.o
.PHONY : src/agent.c.o

src/agent.i: src/agent.c.i
.PHONY : src/agent.i

# target to preprocess a source file
src/agent.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice.dir/build.make CMakeFiles/juice.dir/src/agent.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice-static.dir/build.make CMakeFiles/juice-static.dir/src/agent.c.i
.PHONY : src/agent.c.i

src/agent.s: src/agent.c.s
.PHONY : src/agent.s

# target to generate assembly for a file
src/agent.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice.dir/build.make CMakeFiles/juice.dir/src/agent.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice-static.dir/build.make CMakeFiles/juice-static.dir/src/agent.c.s
.PHONY : src/agent.c.s

src/base64.o: src/base64.c.o
.PHONY : src/base64.o

# target to build an object file
src/base64.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice.dir/build.make CMakeFiles/juice.dir/src/base64.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice-static.dir/build.make CMakeFiles/juice-static.dir/src/base64.c.o
.PHONY : src/base64.c.o

src/base64.i: src/base64.c.i
.PHONY : src/base64.i

# target to preprocess a source file
src/base64.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice.dir/build.make CMakeFiles/juice.dir/src/base64.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice-static.dir/build.make CMakeFiles/juice-static.dir/src/base64.c.i
.PHONY : src/base64.c.i

src/base64.s: src/base64.c.s
.PHONY : src/base64.s

# target to generate assembly for a file
src/base64.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice.dir/build.make CMakeFiles/juice.dir/src/base64.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice-static.dir/build.make CMakeFiles/juice-static.dir/src/base64.c.s
.PHONY : src/base64.c.s

src/conn.o: src/conn.c.o
.PHONY : src/conn.o

# target to build an object file
src/conn.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice.dir/build.make CMakeFiles/juice.dir/src/conn.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice-static.dir/build.make CMakeFiles/juice-static.dir/src/conn.c.o
.PHONY : src/conn.c.o

src/conn.i: src/conn.c.i
.PHONY : src/conn.i

# target to preprocess a source file
src/conn.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice.dir/build.make CMakeFiles/juice.dir/src/conn.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice-static.dir/build.make CMakeFiles/juice-static.dir/src/conn.c.i
.PHONY : src/conn.c.i

src/conn.s: src/conn.c.s
.PHONY : src/conn.s

# target to generate assembly for a file
src/conn.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice.dir/build.make CMakeFiles/juice.dir/src/conn.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice-static.dir/build.make CMakeFiles/juice-static.dir/src/conn.c.s
.PHONY : src/conn.c.s

src/conn_mux.o: src/conn_mux.c.o
.PHONY : src/conn_mux.o

# target to build an object file
src/conn_mux.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice.dir/build.make CMakeFiles/juice.dir/src/conn_mux.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice-static.dir/build.make CMakeFiles/juice-static.dir/src/conn_mux.c.o
.PHONY : src/conn_mux.c.o

src/conn_mux.i: src/conn_mux.c.i
.PHONY : src/conn_mux.i

# target to preprocess a source file
src/conn_mux.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice.dir/build.make CMakeFiles/juice.dir/src/conn_mux.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice-static.dir/build.make CMakeFiles/juice-static.dir/src/conn_mux.c.i
.PHONY : src/conn_mux.c.i

src/conn_mux.s: src/conn_mux.c.s
.PHONY : src/conn_mux.s

# target to generate assembly for a file
src/conn_mux.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice.dir/build.make CMakeFiles/juice.dir/src/conn_mux.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice-static.dir/build.make CMakeFiles/juice-static.dir/src/conn_mux.c.s
.PHONY : src/conn_mux.c.s

src/conn_poll.o: src/conn_poll.c.o
.PHONY : src/conn_poll.o

# target to build an object file
src/conn_poll.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice.dir/build.make CMakeFiles/juice.dir/src/conn_poll.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice-static.dir/build.make CMakeFiles/juice-static.dir/src/conn_poll.c.o
.PHONY : src/conn_poll.c.o

src/conn_poll.i: src/conn_poll.c.i
.PHONY : src/conn_poll.i

# target to preprocess a source file
src/conn_poll.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice.dir/build.make CMakeFiles/juice.dir/src/conn_poll.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice-static.dir/build.make CMakeFiles/juice-static.dir/src/conn_poll.c.i
.PHONY : src/conn_poll.c.i

src/conn_poll.s: src/conn_poll.c.s
.PHONY : src/conn_poll.s

# target to generate assembly for a file
src/conn_poll.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice.dir/build.make CMakeFiles/juice.dir/src/conn_poll.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice-static.dir/build.make CMakeFiles/juice-static.dir/src/conn_poll.c.s
.PHONY : src/conn_poll.c.s

src/conn_thread.o: src/conn_thread.c.o
.PHONY : src/conn_thread.o

# target to build an object file
src/conn_thread.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice.dir/build.make CMakeFiles/juice.dir/src/conn_thread.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice-static.dir/build.make CMakeFiles/juice-static.dir/src/conn_thread.c.o
.PHONY : src/conn_thread.c.o

src/conn_thread.i: src/conn_thread.c.i
.PHONY : src/conn_thread.i

# target to preprocess a source file
src/conn_thread.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice.dir/build.make CMakeFiles/juice.dir/src/conn_thread.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice-static.dir/build.make CMakeFiles/juice-static.dir/src/conn_thread.c.i
.PHONY : src/conn_thread.c.i

src/conn_thread.s: src/conn_thread.c.s
.PHONY : src/conn_thread.s

# target to generate assembly for a file
src/conn_thread.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice.dir/build.make CMakeFiles/juice.dir/src/conn_thread.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice-static.dir/build.make CMakeFiles/juice-static.dir/src/conn_thread.c.s
.PHONY : src/conn_thread.c.s

src/const_time.o: src/const_time.c.o
.PHONY : src/const_time.o

# target to build an object file
src/const_time.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice.dir/build.make CMakeFiles/juice.dir/src/const_time.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice-static.dir/build.make CMakeFiles/juice-static.dir/src/const_time.c.o
.PHONY : src/const_time.c.o

src/const_time.i: src/const_time.c.i
.PHONY : src/const_time.i

# target to preprocess a source file
src/const_time.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice.dir/build.make CMakeFiles/juice.dir/src/const_time.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice-static.dir/build.make CMakeFiles/juice-static.dir/src/const_time.c.i
.PHONY : src/const_time.c.i

src/const_time.s: src/const_time.c.s
.PHONY : src/const_time.s

# target to generate assembly for a file
src/const_time.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice.dir/build.make CMakeFiles/juice.dir/src/const_time.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice-static.dir/build.make CMakeFiles/juice-static.dir/src/const_time.c.s
.PHONY : src/const_time.c.s

src/crc32.o: src/crc32.c.o
.PHONY : src/crc32.o

# target to build an object file
src/crc32.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice.dir/build.make CMakeFiles/juice.dir/src/crc32.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice-static.dir/build.make CMakeFiles/juice-static.dir/src/crc32.c.o
.PHONY : src/crc32.c.o

src/crc32.i: src/crc32.c.i
.PHONY : src/crc32.i

# target to preprocess a source file
src/crc32.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice.dir/build.make CMakeFiles/juice.dir/src/crc32.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice-static.dir/build.make CMakeFiles/juice-static.dir/src/crc32.c.i
.PHONY : src/crc32.c.i

src/crc32.s: src/crc32.c.s
.PHONY : src/crc32.s

# target to generate assembly for a file
src/crc32.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice.dir/build.make CMakeFiles/juice.dir/src/crc32.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice-static.dir/build.make CMakeFiles/juice-static.dir/src/crc32.c.s
.PHONY : src/crc32.c.s

src/hash.o: src/hash.c.o
.PHONY : src/hash.o

# target to build an object file
src/hash.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice.dir/build.make CMakeFiles/juice.dir/src/hash.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice-static.dir/build.make CMakeFiles/juice-static.dir/src/hash.c.o
.PHONY : src/hash.c.o

src/hash.i: src/hash.c.i
.PHONY : src/hash.i

# target to preprocess a source file
src/hash.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice.dir/build.make CMakeFiles/juice.dir/src/hash.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice-static.dir/build.make CMakeFiles/juice-static.dir/src/hash.c.i
.PHONY : src/hash.c.i

src/hash.s: src/hash.c.s
.PHONY : src/hash.s

# target to generate assembly for a file
src/hash.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice.dir/build.make CMakeFiles/juice.dir/src/hash.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice-static.dir/build.make CMakeFiles/juice-static.dir/src/hash.c.s
.PHONY : src/hash.c.s

src/hmac.o: src/hmac.c.o
.PHONY : src/hmac.o

# target to build an object file
src/hmac.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice.dir/build.make CMakeFiles/juice.dir/src/hmac.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice-static.dir/build.make CMakeFiles/juice-static.dir/src/hmac.c.o
.PHONY : src/hmac.c.o

src/hmac.i: src/hmac.c.i
.PHONY : src/hmac.i

# target to preprocess a source file
src/hmac.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice.dir/build.make CMakeFiles/juice.dir/src/hmac.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice-static.dir/build.make CMakeFiles/juice-static.dir/src/hmac.c.i
.PHONY : src/hmac.c.i

src/hmac.s: src/hmac.c.s
.PHONY : src/hmac.s

# target to generate assembly for a file
src/hmac.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice.dir/build.make CMakeFiles/juice.dir/src/hmac.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice-static.dir/build.make CMakeFiles/juice-static.dir/src/hmac.c.s
.PHONY : src/hmac.c.s

src/ice.o: src/ice.c.o
.PHONY : src/ice.o

# target to build an object file
src/ice.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice.dir/build.make CMakeFiles/juice.dir/src/ice.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice-static.dir/build.make CMakeFiles/juice-static.dir/src/ice.c.o
.PHONY : src/ice.c.o

src/ice.i: src/ice.c.i
.PHONY : src/ice.i

# target to preprocess a source file
src/ice.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice.dir/build.make CMakeFiles/juice.dir/src/ice.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice-static.dir/build.make CMakeFiles/juice-static.dir/src/ice.c.i
.PHONY : src/ice.c.i

src/ice.s: src/ice.c.s
.PHONY : src/ice.s

# target to generate assembly for a file
src/ice.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice.dir/build.make CMakeFiles/juice.dir/src/ice.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice-static.dir/build.make CMakeFiles/juice-static.dir/src/ice.c.s
.PHONY : src/ice.c.s

src/juice.o: src/juice.c.o
.PHONY : src/juice.o

# target to build an object file
src/juice.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice.dir/build.make CMakeFiles/juice.dir/src/juice.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice-static.dir/build.make CMakeFiles/juice-static.dir/src/juice.c.o
.PHONY : src/juice.c.o

src/juice.i: src/juice.c.i
.PHONY : src/juice.i

# target to preprocess a source file
src/juice.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice.dir/build.make CMakeFiles/juice.dir/src/juice.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice-static.dir/build.make CMakeFiles/juice-static.dir/src/juice.c.i
.PHONY : src/juice.c.i

src/juice.s: src/juice.c.s
.PHONY : src/juice.s

# target to generate assembly for a file
src/juice.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice.dir/build.make CMakeFiles/juice.dir/src/juice.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice-static.dir/build.make CMakeFiles/juice-static.dir/src/juice.c.s
.PHONY : src/juice.c.s

src/log.o: src/log.c.o
.PHONY : src/log.o

# target to build an object file
src/log.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice.dir/build.make CMakeFiles/juice.dir/src/log.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice-static.dir/build.make CMakeFiles/juice-static.dir/src/log.c.o
.PHONY : src/log.c.o

src/log.i: src/log.c.i
.PHONY : src/log.i

# target to preprocess a source file
src/log.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice.dir/build.make CMakeFiles/juice.dir/src/log.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice-static.dir/build.make CMakeFiles/juice-static.dir/src/log.c.i
.PHONY : src/log.c.i

src/log.s: src/log.c.s
.PHONY : src/log.s

# target to generate assembly for a file
src/log.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice.dir/build.make CMakeFiles/juice.dir/src/log.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice-static.dir/build.make CMakeFiles/juice-static.dir/src/log.c.s
.PHONY : src/log.c.s

src/random.o: src/random.c.o
.PHONY : src/random.o

# target to build an object file
src/random.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice.dir/build.make CMakeFiles/juice.dir/src/random.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice-static.dir/build.make CMakeFiles/juice-static.dir/src/random.c.o
.PHONY : src/random.c.o

src/random.i: src/random.c.i
.PHONY : src/random.i

# target to preprocess a source file
src/random.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice.dir/build.make CMakeFiles/juice.dir/src/random.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice-static.dir/build.make CMakeFiles/juice-static.dir/src/random.c.i
.PHONY : src/random.c.i

src/random.s: src/random.c.s
.PHONY : src/random.s

# target to generate assembly for a file
src/random.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice.dir/build.make CMakeFiles/juice.dir/src/random.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice-static.dir/build.make CMakeFiles/juice-static.dir/src/random.c.s
.PHONY : src/random.c.s

src/server.o: src/server.c.o
.PHONY : src/server.o

# target to build an object file
src/server.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice.dir/build.make CMakeFiles/juice.dir/src/server.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice-static.dir/build.make CMakeFiles/juice-static.dir/src/server.c.o
.PHONY : src/server.c.o

src/server.i: src/server.c.i
.PHONY : src/server.i

# target to preprocess a source file
src/server.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice.dir/build.make CMakeFiles/juice.dir/src/server.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice-static.dir/build.make CMakeFiles/juice-static.dir/src/server.c.i
.PHONY : src/server.c.i

src/server.s: src/server.c.s
.PHONY : src/server.s

# target to generate assembly for a file
src/server.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice.dir/build.make CMakeFiles/juice.dir/src/server.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice-static.dir/build.make CMakeFiles/juice-static.dir/src/server.c.s
.PHONY : src/server.c.s

src/stun.o: src/stun.c.o
.PHONY : src/stun.o

# target to build an object file
src/stun.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice.dir/build.make CMakeFiles/juice.dir/src/stun.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice-static.dir/build.make CMakeFiles/juice-static.dir/src/stun.c.o
.PHONY : src/stun.c.o

src/stun.i: src/stun.c.i
.PHONY : src/stun.i

# target to preprocess a source file
src/stun.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice.dir/build.make CMakeFiles/juice.dir/src/stun.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice-static.dir/build.make CMakeFiles/juice-static.dir/src/stun.c.i
.PHONY : src/stun.c.i

src/stun.s: src/stun.c.s
.PHONY : src/stun.s

# target to generate assembly for a file
src/stun.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice.dir/build.make CMakeFiles/juice.dir/src/stun.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice-static.dir/build.make CMakeFiles/juice-static.dir/src/stun.c.s
.PHONY : src/stun.c.s

src/timestamp.o: src/timestamp.c.o
.PHONY : src/timestamp.o

# target to build an object file
src/timestamp.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice.dir/build.make CMakeFiles/juice.dir/src/timestamp.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice-static.dir/build.make CMakeFiles/juice-static.dir/src/timestamp.c.o
.PHONY : src/timestamp.c.o

src/timestamp.i: src/timestamp.c.i
.PHONY : src/timestamp.i

# target to preprocess a source file
src/timestamp.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice.dir/build.make CMakeFiles/juice.dir/src/timestamp.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice-static.dir/build.make CMakeFiles/juice-static.dir/src/timestamp.c.i
.PHONY : src/timestamp.c.i

src/timestamp.s: src/timestamp.c.s
.PHONY : src/timestamp.s

# target to generate assembly for a file
src/timestamp.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice.dir/build.make CMakeFiles/juice.dir/src/timestamp.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice-static.dir/build.make CMakeFiles/juice-static.dir/src/timestamp.c.s
.PHONY : src/timestamp.c.s

src/turn.o: src/turn.c.o
.PHONY : src/turn.o

# target to build an object file
src/turn.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice.dir/build.make CMakeFiles/juice.dir/src/turn.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice-static.dir/build.make CMakeFiles/juice-static.dir/src/turn.c.o
.PHONY : src/turn.c.o

src/turn.i: src/turn.c.i
.PHONY : src/turn.i

# target to preprocess a source file
src/turn.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice.dir/build.make CMakeFiles/juice.dir/src/turn.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice-static.dir/build.make CMakeFiles/juice-static.dir/src/turn.c.i
.PHONY : src/turn.c.i

src/turn.s: src/turn.c.s
.PHONY : src/turn.s

# target to generate assembly for a file
src/turn.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice.dir/build.make CMakeFiles/juice.dir/src/turn.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice-static.dir/build.make CMakeFiles/juice-static.dir/src/turn.c.s
.PHONY : src/turn.c.s

src/udp.o: src/udp.c.o
.PHONY : src/udp.o

# target to build an object file
src/udp.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice.dir/build.make CMakeFiles/juice.dir/src/udp.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice-static.dir/build.make CMakeFiles/juice-static.dir/src/udp.c.o
.PHONY : src/udp.c.o

src/udp.i: src/udp.c.i
.PHONY : src/udp.i

# target to preprocess a source file
src/udp.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice.dir/build.make CMakeFiles/juice.dir/src/udp.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice-static.dir/build.make CMakeFiles/juice-static.dir/src/udp.c.i
.PHONY : src/udp.c.i

src/udp.s: src/udp.c.s
.PHONY : src/udp.s

# target to generate assembly for a file
src/udp.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice.dir/build.make CMakeFiles/juice.dir/src/udp.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice-static.dir/build.make CMakeFiles/juice-static.dir/src/udp.c.s
.PHONY : src/udp.c.s

test/base64.o: test/base64.c.o
.PHONY : test/base64.o

# target to build an object file
test/base64.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice-tests.dir/build.make CMakeFiles/juice-tests.dir/test/base64.c.o
.PHONY : test/base64.c.o

test/base64.i: test/base64.c.i
.PHONY : test/base64.i

# target to preprocess a source file
test/base64.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice-tests.dir/build.make CMakeFiles/juice-tests.dir/test/base64.c.i
.PHONY : test/base64.c.i

test/base64.s: test/base64.c.s
.PHONY : test/base64.s

# target to generate assembly for a file
test/base64.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice-tests.dir/build.make CMakeFiles/juice-tests.dir/test/base64.c.s
.PHONY : test/base64.c.s

test/bind.o: test/bind.c.o
.PHONY : test/bind.o

# target to build an object file
test/bind.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice-tests.dir/build.make CMakeFiles/juice-tests.dir/test/bind.c.o
.PHONY : test/bind.c.o

test/bind.i: test/bind.c.i
.PHONY : test/bind.i

# target to preprocess a source file
test/bind.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice-tests.dir/build.make CMakeFiles/juice-tests.dir/test/bind.c.i
.PHONY : test/bind.c.i

test/bind.s: test/bind.c.s
.PHONY : test/bind.s

# target to generate assembly for a file
test/bind.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice-tests.dir/build.make CMakeFiles/juice-tests.dir/test/bind.c.s
.PHONY : test/bind.c.s

test/conflict.o: test/conflict.c.o
.PHONY : test/conflict.o

# target to build an object file
test/conflict.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice-tests.dir/build.make CMakeFiles/juice-tests.dir/test/conflict.c.o
.PHONY : test/conflict.c.o

test/conflict.i: test/conflict.c.i
.PHONY : test/conflict.i

# target to preprocess a source file
test/conflict.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice-tests.dir/build.make CMakeFiles/juice-tests.dir/test/conflict.c.i
.PHONY : test/conflict.c.i

test/conflict.s: test/conflict.c.s
.PHONY : test/conflict.s

# target to generate assembly for a file
test/conflict.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice-tests.dir/build.make CMakeFiles/juice-tests.dir/test/conflict.c.s
.PHONY : test/conflict.c.s

test/connectivity.o: test/connectivity.c.o
.PHONY : test/connectivity.o

# target to build an object file
test/connectivity.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice-tests.dir/build.make CMakeFiles/juice-tests.dir/test/connectivity.c.o
.PHONY : test/connectivity.c.o

test/connectivity.i: test/connectivity.c.i
.PHONY : test/connectivity.i

# target to preprocess a source file
test/connectivity.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice-tests.dir/build.make CMakeFiles/juice-tests.dir/test/connectivity.c.i
.PHONY : test/connectivity.c.i

test/connectivity.s: test/connectivity.c.s
.PHONY : test/connectivity.s

# target to generate assembly for a file
test/connectivity.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice-tests.dir/build.make CMakeFiles/juice-tests.dir/test/connectivity.c.s
.PHONY : test/connectivity.c.s

test/crc32.o: test/crc32.c.o
.PHONY : test/crc32.o

# target to build an object file
test/crc32.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice-tests.dir/build.make CMakeFiles/juice-tests.dir/test/crc32.c.o
.PHONY : test/crc32.c.o

test/crc32.i: test/crc32.c.i
.PHONY : test/crc32.i

# target to preprocess a source file
test/crc32.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice-tests.dir/build.make CMakeFiles/juice-tests.dir/test/crc32.c.i
.PHONY : test/crc32.c.i

test/crc32.s: test/crc32.c.s
.PHONY : test/crc32.s

# target to generate assembly for a file
test/crc32.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice-tests.dir/build.make CMakeFiles/juice-tests.dir/test/crc32.c.s
.PHONY : test/crc32.c.s

test/gathering.o: test/gathering.c.o
.PHONY : test/gathering.o

# target to build an object file
test/gathering.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice-tests.dir/build.make CMakeFiles/juice-tests.dir/test/gathering.c.o
.PHONY : test/gathering.c.o

test/gathering.i: test/gathering.c.i
.PHONY : test/gathering.i

# target to preprocess a source file
test/gathering.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice-tests.dir/build.make CMakeFiles/juice-tests.dir/test/gathering.c.i
.PHONY : test/gathering.c.i

test/gathering.s: test/gathering.c.s
.PHONY : test/gathering.s

# target to generate assembly for a file
test/gathering.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice-tests.dir/build.make CMakeFiles/juice-tests.dir/test/gathering.c.s
.PHONY : test/gathering.c.s

test/main.o: test/main.c.o
.PHONY : test/main.o

# target to build an object file
test/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice-tests.dir/build.make CMakeFiles/juice-tests.dir/test/main.c.o
.PHONY : test/main.c.o

test/main.i: test/main.c.i
.PHONY : test/main.i

# target to preprocess a source file
test/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice-tests.dir/build.make CMakeFiles/juice-tests.dir/test/main.c.i
.PHONY : test/main.c.i

test/main.s: test/main.c.s
.PHONY : test/main.s

# target to generate assembly for a file
test/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice-tests.dir/build.make CMakeFiles/juice-tests.dir/test/main.c.s
.PHONY : test/main.c.s

test/mux.o: test/mux.c.o
.PHONY : test/mux.o

# target to build an object file
test/mux.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice-tests.dir/build.make CMakeFiles/juice-tests.dir/test/mux.c.o
.PHONY : test/mux.c.o

test/mux.i: test/mux.c.i
.PHONY : test/mux.i

# target to preprocess a source file
test/mux.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice-tests.dir/build.make CMakeFiles/juice-tests.dir/test/mux.c.i
.PHONY : test/mux.c.i

test/mux.s: test/mux.c.s
.PHONY : test/mux.s

# target to generate assembly for a file
test/mux.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice-tests.dir/build.make CMakeFiles/juice-tests.dir/test/mux.c.s
.PHONY : test/mux.c.s

test/notrickle.o: test/notrickle.c.o
.PHONY : test/notrickle.o

# target to build an object file
test/notrickle.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice-tests.dir/build.make CMakeFiles/juice-tests.dir/test/notrickle.c.o
.PHONY : test/notrickle.c.o

test/notrickle.i: test/notrickle.c.i
.PHONY : test/notrickle.i

# target to preprocess a source file
test/notrickle.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice-tests.dir/build.make CMakeFiles/juice-tests.dir/test/notrickle.c.i
.PHONY : test/notrickle.c.i

test/notrickle.s: test/notrickle.c.s
.PHONY : test/notrickle.s

# target to generate assembly for a file
test/notrickle.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice-tests.dir/build.make CMakeFiles/juice-tests.dir/test/notrickle.c.s
.PHONY : test/notrickle.c.s

test/server.o: test/server.c.o
.PHONY : test/server.o

# target to build an object file
test/server.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice-tests.dir/build.make CMakeFiles/juice-tests.dir/test/server.c.o
.PHONY : test/server.c.o

test/server.i: test/server.c.i
.PHONY : test/server.i

# target to preprocess a source file
test/server.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice-tests.dir/build.make CMakeFiles/juice-tests.dir/test/server.c.i
.PHONY : test/server.c.i

test/server.s: test/server.c.s
.PHONY : test/server.s

# target to generate assembly for a file
test/server.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice-tests.dir/build.make CMakeFiles/juice-tests.dir/test/server.c.s
.PHONY : test/server.c.s

test/stun.o: test/stun.c.o
.PHONY : test/stun.o

# target to build an object file
test/stun.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice-tests.dir/build.make CMakeFiles/juice-tests.dir/test/stun.c.o
.PHONY : test/stun.c.o

test/stun.i: test/stun.c.i
.PHONY : test/stun.i

# target to preprocess a source file
test/stun.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice-tests.dir/build.make CMakeFiles/juice-tests.dir/test/stun.c.i
.PHONY : test/stun.c.i

test/stun.s: test/stun.c.s
.PHONY : test/stun.s

# target to generate assembly for a file
test/stun.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice-tests.dir/build.make CMakeFiles/juice-tests.dir/test/stun.c.s
.PHONY : test/stun.c.s

test/thread.o: test/thread.c.o
.PHONY : test/thread.o

# target to build an object file
test/thread.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice-tests.dir/build.make CMakeFiles/juice-tests.dir/test/thread.c.o
.PHONY : test/thread.c.o

test/thread.i: test/thread.c.i
.PHONY : test/thread.i

# target to preprocess a source file
test/thread.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice-tests.dir/build.make CMakeFiles/juice-tests.dir/test/thread.c.i
.PHONY : test/thread.c.i

test/thread.s: test/thread.c.s
.PHONY : test/thread.s

# target to generate assembly for a file
test/thread.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice-tests.dir/build.make CMakeFiles/juice-tests.dir/test/thread.c.s
.PHONY : test/thread.c.s

test/turn.o: test/turn.c.o
.PHONY : test/turn.o

# target to build an object file
test/turn.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice-tests.dir/build.make CMakeFiles/juice-tests.dir/test/turn.c.o
.PHONY : test/turn.c.o

test/turn.i: test/turn.c.i
.PHONY : test/turn.i

# target to preprocess a source file
test/turn.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice-tests.dir/build.make CMakeFiles/juice-tests.dir/test/turn.c.i
.PHONY : test/turn.c.i

test/turn.s: test/turn.c.s
.PHONY : test/turn.s

# target to generate assembly for a file
test/turn.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juice-tests.dir/build.make CMakeFiles/juice-tests.dir/test/turn.c.s
.PHONY : test/turn.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... juice"
	@echo "... juice-static"
	@echo "... juice-tests"
	@echo "... src/addr.o"
	@echo "... src/addr.i"
	@echo "... src/addr.s"
	@echo "... src/agent.o"
	@echo "... src/agent.i"
	@echo "... src/agent.s"
	@echo "... src/base64.o"
	@echo "... src/base64.i"
	@echo "... src/base64.s"
	@echo "... src/conn.o"
	@echo "... src/conn.i"
	@echo "... src/conn.s"
	@echo "... src/conn_mux.o"
	@echo "... src/conn_mux.i"
	@echo "... src/conn_mux.s"
	@echo "... src/conn_poll.o"
	@echo "... src/conn_poll.i"
	@echo "... src/conn_poll.s"
	@echo "... src/conn_thread.o"
	@echo "... src/conn_thread.i"
	@echo "... src/conn_thread.s"
	@echo "... src/const_time.o"
	@echo "... src/const_time.i"
	@echo "... src/const_time.s"
	@echo "... src/crc32.o"
	@echo "... src/crc32.i"
	@echo "... src/crc32.s"
	@echo "... src/hash.o"
	@echo "... src/hash.i"
	@echo "... src/hash.s"
	@echo "... src/hmac.o"
	@echo "... src/hmac.i"
	@echo "... src/hmac.s"
	@echo "... src/ice.o"
	@echo "... src/ice.i"
	@echo "... src/ice.s"
	@echo "... src/juice.o"
	@echo "... src/juice.i"
	@echo "... src/juice.s"
	@echo "... src/log.o"
	@echo "... src/log.i"
	@echo "... src/log.s"
	@echo "... src/random.o"
	@echo "... src/random.i"
	@echo "... src/random.s"
	@echo "... src/server.o"
	@echo "... src/server.i"
	@echo "... src/server.s"
	@echo "... src/stun.o"
	@echo "... src/stun.i"
	@echo "... src/stun.s"
	@echo "... src/timestamp.o"
	@echo "... src/timestamp.i"
	@echo "... src/timestamp.s"
	@echo "... src/turn.o"
	@echo "... src/turn.i"
	@echo "... src/turn.s"
	@echo "... src/udp.o"
	@echo "... src/udp.i"
	@echo "... src/udp.s"
	@echo "... test/base64.o"
	@echo "... test/base64.i"
	@echo "... test/base64.s"
	@echo "... test/bind.o"
	@echo "... test/bind.i"
	@echo "... test/bind.s"
	@echo "... test/conflict.o"
	@echo "... test/conflict.i"
	@echo "... test/conflict.s"
	@echo "... test/connectivity.o"
	@echo "... test/connectivity.i"
	@echo "... test/connectivity.s"
	@echo "... test/crc32.o"
	@echo "... test/crc32.i"
	@echo "... test/crc32.s"
	@echo "... test/gathering.o"
	@echo "... test/gathering.i"
	@echo "... test/gathering.s"
	@echo "... test/main.o"
	@echo "... test/main.i"
	@echo "... test/main.s"
	@echo "... test/mux.o"
	@echo "... test/mux.i"
	@echo "... test/mux.s"
	@echo "... test/notrickle.o"
	@echo "... test/notrickle.i"
	@echo "... test/notrickle.s"
	@echo "... test/server.o"
	@echo "... test/server.i"
	@echo "... test/server.s"
	@echo "... test/stun.o"
	@echo "... test/stun.i"
	@echo "... test/stun.s"
	@echo "... test/thread.o"
	@echo "... test/thread.i"
	@echo "... test/thread.s"
	@echo "... test/turn.o"
	@echo "... test/turn.i"
	@echo "... test/turn.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

